version: '3'
services:
    mongodb:
        image: mongo:4.4.19-focal
        container_name: mongodb
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin 
            - MONGO_INITDB_ROOT_PASSWORD=admin
        networks:
            app-net: {}

    emongodb:
        image: mongo-express:latest
        container_name: emongodb
        restart: always
        ports:
            - 8080:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin 
            - ME_CONFIG_MONGODB_ADMINPASSWORD=admin 
            - ME_CONFIG_MONGODB_SERVER=mongodb
        networks:
            app-net: {}

    papp:
        image: app
        container_name: papp
        ports:
            - 80:5000
        networks:
            app-net: {}

networks:
    app-net: {}
